export const defaultSEOConfig = {
  title: "Building Blocks of Bravery - Children's Books by Mark Baranov",
  description: "Discover the Building Blocks of Bravery series - inspiring children's books that help young readers navigate life's challenges with courage and confidence. Written by Mark Baranov, these heartwarming stories teach valuable lessons about resilience, self-discovery, and inner strength.",
  image: "https://i.ibb.co/7Kh8RVT/metalisanft-httpss-mj-run-Kwb-Cmqc-Pbp-Q-httpss-mj-runkey-o6-FXm-Yg-s-77ee76a1-db98-48b5-a614-b70da4.jpg",
  url: "https://buildingblocksofbravery.com",
  type: "website",
  author: "Mark Baranov",
  keywords: [
    "children's books",
    "kids books",
    "educational books",
    "picture books",
    "Building Blocks of Bravery",
    "Mark Baranov",
    "bravery",
    "courage",
    "resilience",
    "self-esteem",
    "emotional intelligence",
    "character development",
    "bedtime stories",
    "inspirational stories",
    "children's literature",
    "parenting resources",
    "teaching materials",
    "reading age 5-12",
    "moral stories",
    "life lessons for kids"
  ].join(", ")
};